name: Test Suite CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:
    name: API Functional Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #Clone your repo onto that fresh machine.
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -e .
      - name: Run API tests
        run: pytest tests/api/ -v --alluredir=reports/allure-results/api
      - name: Upload results
        if: always() # means "do this even if the tests failed"
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: reports/allure-results/api

  security-tests:
    name: Security Smoke Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -e .
      - name: Run security tests
        run: pytest tests/security/ -v --alluredir=reports/allure-results/security
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: security-test-results
          path: reports/allure-results/security

  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -e .
      - name: Run contract tests
        run: pytest tests/contract/ -v --alluredir=reports/allure-results/contract
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contract-test-results
          path: reports/allure-results/contract

  e2e-tests:
    name: E2E UI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install -e ".[e2e]"
      - name: Install Playwright browsers
        run: playwright install chromium --with-deps
      - name: Run E2E tests
        run: pytest tests/e2e/ -v --alluredir=reports/allure-results/e2e
      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: reports/allure-results/e2e

  allure-report:
    name: Publish Allure Report
    runs-on: ubuntu-latest
    needs: [api-tests, security-tests, contract-tests, e2e-tests]
    if: always()
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all results
        uses: actions/download-artifact@v4
        with:
          path: reports/allure-results
          merge-multiple: true
      - name: Install Allure
        run: |
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.30.0/allure-2.30.0.tgz | tar -xz
          echo "$PWD/allure-2.30.0/bin" >> $GITHUB_PATH
      - name: Generate Allure Report
        run: allure generate reports/allure-results -o reports/allure-report --clean
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: reports/allure-report


#You push code
#     ↓
#GitHub sees "on: push" in ci.yml
#     ↓
#Spins up 4 fresh Linux machines (free)
#     ↓
#Each runs its test layer in parallel
#     ↓
#All finish → 5th machine generates Allure report
#     ↓
#Green ✓ or Red ✗ on your commit
#     ↓
#Report published to GitHub Pages